### ISSUE TITLE
Does not render x-markdown

### ISSUE THREAD

**Issue by wzr1337** [usrz/js-markdown-extension#3]
Not rendering markdown for content type "text/x-markdown"

**Comment by alcortesm** [comment]
https://github.com/usrz/js-markdown-extension/pull/2

**Comment by xieranmaya** [comment]
I forked the project and added the support for text/x-markdown and uploaded the extension to Chrome Store: https://chrome.google.com/webstore/detail/github-flavored-markdown/fifkmhcgoobihkepohlhpkabplahglbo

**Comment by pfumagalli** [comment]
Merged #2
