### ISSUE TITLE
Local file support

### ISSUE THREAD

**Issue by syepes** [usrz/js-markdown-extension#5]
It would be nice to have support for reading (previewing) local file "file:///C:/"

**Comment by pfumagalli** [comment]
It's fully supported. By default chrome does not allow extensions to read your files, but you can definitely allow it by going to chrome://extensions/ and ticking "Allow access to file URLs".

On my Mac it looks like this:

![screen shot 2016-10-17 at 14 37 00](https://cloud.githubusercontent.com/assets/366777/19437819/5237e18c-9477-11e6-9859-1395148d3d93.png)

**Comment by syepes** [comment]
@pfumagalli Thanks for the tip!
