### ISSUE TITLE
incorrect rendering: pipe charcacter `|` in ticks in table breaks table

### ISSUE THREAD

**Issue by powerslave** [usrz/js-markdown-extension#6]
this markdown renders incorrectly with js-markdown-extension, compared with github
```
| ---------  |
| `|` (pipe) |
```

**broken** with js-markdown-extension
![image](https://cloud.githubusercontent.com/assets/853599/20194143/8169858c-a791-11e6-8060-483f079c2b7b.png)

**expected** on github
![image](https://cloud.githubusercontent.com/assets/853599/20194170/9fb9cb0a-a791-11e6-8b46-c0fd4fae7b97.png)

**Comment by pfumagalli** [comment]
This is actually an _issue_ with `marked` itself: chjj/marked#595.

When they'll fix it, I'll pick up the release...
